### PR TITLE
Fix race condition in cache eviction

### PR DESCRIPTION
**Pull request by hannes-ucsc**
Continued from #163

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Re test failures, would you prefer to add the `futures` backport as a test dependency or to skip the test on Python 2.x?

**Comment by beowulfenator** [comment]
Please pull this, I'm having the exact same problem (big cache in a multithreaded application and it throws KeyError intermittently)

**Comment by jamesls** [comment]
I'll take a look at this today.

**Comment by beowulfenator** [comment]
Thank you!

**Pull request merged**
