### PR TITLE
Add support for Python 3.12 and drop EOL <= 3.7

### PR DESCRIPTION
**Pull request by hugovk**
The [Python 3.12 release candidate is out!](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

Also drop EOL Python <= 3.7, helps https://github.com/jmespath/jmespath.py/pull/313.

See also:

* https://dev.to/hugovk/help-test-python-312-beta-1508/
* https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
* https://setuptools.pypa.io/en/latest/build_meta.html

### CODE REVIEW

**Comment by khneal** [comment]
This would be nice to have.
@jamesls - are you available to review+approve+merge+release?

**Comment by hugovk** [comment]
Closing as this PR is one year old, and the last commit was in March 2023.

Happy to re-open if there's any interest!

**Comment by khneal** [comment]
@hugovk - I’m still interested. Please reopen and consider merging as soon as is convenient. 
Python 3.12 has been GA for almost a year, 3.13 GA GA release is expected in just over one month, and then 3.8 will be EOL about a month after that.

**Comment by hugovk** [comment]
I don't have merge permissions here so unfortunately there's no point re-opening unless a maintainer is going to merge this.

**Pull request closed without merging**
