### PR TITLE
None to NoneType

### PR DESCRIPTION
**Pull request by ophiry**
bugfix: the type of None should be NoneType instead of None

### CODE REVIEW

**Comment by jamesls** [comment]
Not sure why codecov is complaining.

Could you add a test for this change that demonstrates the issue?  Once we have that I'll go ahead and merge.  Thanks.

**Comment by gmega** [comment]
Hi there @ophiry @jamesls: I've written the test so that we can see this change merged. :-) I don't see an easy way to integrate my changes in this pull request though. Should I open a new one? Thanks.

**Comment by jamesls** [comment]
@gmega Feel free to open a new one.  Thanks!

**Comment by jamesls** [comment]
Fixed in https://github.com/jmespath/jmespath.py/pull/145

**Pull request closed without merging**
