### PR TITLE
Drop support for EOL Python 2.6 and 3.3

### PR DESCRIPTION
**Pull request by hugovk**
Python 2.6 and 3.3 are EOL (2.6 in 2013 and 3.3 in 2017) and no longer receiving security updates (or any updates) from the core Python team. They're also relatively little used.

Here's the pip installs for JMESPath from PyPI for July 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  84.97% |      6,859,760 |
| 3.6            |   8.74% |        705,206 |
| 3.5            |   3.93% |        317,543 |
| 3.4            |   1.45% |        117,063 |
| 3.7            |   0.48% |         38,496 |
| 2.6            |   0.43% |         34,353 |
| 3.3            |   0.00% |            381 |
| 3.8            |   0.00% |             12 |
| None           |   0.00% |              2 |
| 3.2            |   0.00% |              1 |
| Total          |         |      8,072,817 |

Source: `pypinfo --start-date 2018-07-01 --end-date 2018-07-31 --percent --markdown jmespath pyversion`

This PR:

* Drops support for EOL Python 2.6 (same as https://github.com/jmespath/jmespath.py/pull/114)
* Drops support for EOL Python 3.3
* Upgrades Python syntax with https://github.com/asottile/pyupgrade
* Fixes some code inspection warnings
* Adds python_requires to help pip: https://packaging.python.org/guides/dropping-older-python-versions/

### CODE REVIEW

**Comment by jamesls** [comment]
Thanks for the pull request.  I would love to drop support for python2.6, but this would affect many downstream dependencies that use jmespath.  If we're going to do this, we'd need to have a deprecation period first to give people a heads up.

**Comment by hugovk** [comment]
Deprecation before removal is sensible. 

Please see https://github.com/jmespath/jmespath.py/pull/175 for some suggestions.

(This PR rebased to resolve conflict.)

**Comment by hugovk** [comment]
Here's the pip installs for July 2019:

| category | percent | downloads  |
|----------|--------:|-----------:|
| 2.7      |  67.24% | 27,486,612 |
| 3.6      |  11.80% |  4,823,393 |
| 3.7      |   7.10% |  2,901,032 |
| 2.6      |   5.08% |  2,077,811 |
| 3.5      |   4.65% |  1,900,406 |
| 3.4      |   3.73% |  1,525,865 |
| null     |   0.39% |    159,024 |
| 3.8      |   0.01% |      4,058 |
| 3.3      |   0.00% |        731 |
| 3.2      |   0.00% |          7 |
| 3.9      |   0.00% |          5 |
| 3.1      |   0.00% |          2 |
| Total    |         | 40,878,946 |

Source: `pip install -U pypistats && pypistats python_minor jmespath --last-month`

**Comment by hugovk** [comment]
The 2.6/3.3 deprecations haven't been released yet.

Python 3.4 is also now EOL, shall we include it in the deprecations too, and then remove it here?

**Comment by jamesls** [comment]
The 2.6/3.3 deprecations are now part of the 0.10.0 release.  I don't mind moving quickly on the 3.4 deprecation, but I'd want to remove 2.6/3.3 support first.

**Comment by hugovk** [comment]
@jamesls Hello, do you think it may be time to merge this, now the deprecations have been released in 0.10.0?

**Comment by bsolomon1124** [comment]
@jamesls is there any type of formal deprecation plan for 2.7?

**Pull request closed without merging**
